version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance  # Se usar pasta instance para o banco, adapte conforme seu projeto
      - ./users.db:/app/users.db  # Mapeia o arquivo do SQLite (se quiser)
    environment:
      - FLASK_ENV=development  # opcional, para ambiente dev

volumes:
  sqlite_data:
